import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Header from "./sections/Header";
import { Instrument_Serif } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const instrumentSerif = Instrument_Serif({
  weight: '400',
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-instrument-serif',  // exposes it as a CSS variable
})
const helveticaNeue = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueUltraLight.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueUltraLightItalic.otf",
      weight: "100",
      style: "italic",
    },

    {
      path: "./fonts/HelveticaNeue/HelveticaNeueThin.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueThinItalic.otf",
      weight: "200",
      style: "italic",
    },

    {
      path: "./fonts/HelveticaNeue/HelveticaNeueLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueLightItalic.otf",
      weight: "300",
      style: "italic",
    },

    {
      path: "./fonts/HelveticaNeue/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueItalic.ttf",
      weight: "400",
      style: "italic",
    },

    {
      path: "./fonts/HelveticaNeue/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueMediumItalic.otf",
      weight: "500",
      style: "italic",
    },

    {
      path: "./fonts/HelveticaNeue/HelveticaNeueBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueBoldItalic.otf",
      weight: "700",
      style: "italic",
    },

    {
      path: "./fonts/HelveticaNeue/HelveticaNeueHeavy.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueHeavyItalic.otf",
      weight: "800",
      style: "italic",
    },

    {
      path: "./fonts/HelveticaNeue/HelveticaNeueBlack.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue/HelveticaNeueBlackItalic.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-helvetica",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${helveticaNeue.variable}  ${instrumentSerif.variable} antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">  
   {children}</body>
    </html>
  );
}
